apiVersion: v1
kind: Pod
metadata:
  name: configmap-demo-1
spec:
  containers:
    - name: demo-container
      image: nginx:latest
      envFrom:
        - configMapRef:
            name: configmap-1