apiVersion: v1
kind: Pod
metadata:
  name: configmap-demo-2
spec:
  containers:
  - name: envars-test-container
    image: nginx
    env:
    - name: NAME
      valueFrom:
        configMapKeyRef:
          name: configmap-2
          key: name