apiVersion: v1
kind: Pod
metadata:
  name: configmap-demo-3
spec:
  containers:
    - name: nginx-container
      image: nginx:latest
      volumeMounts:
        - name: config
          mountPath: /etc/config
  volumes:
    - name: config
      configMap:
        name: configmap-3