apiVersion: v1
kind: Pod
metadata:
  name: envar-demo
  labels:
    purpose: demonstrate-envars
spec:
  containers:
  - name: envar-demo-container
    image: wordpress
    env:
    - name: WORDPRESS_VERSION
      value: "4.2.2"
    - name: WORDPRESS_USER
      value: "admin"
    command: ["echo"]
    args: ["$(WORDPRESS_VERSION) $(WORDPRESS_USER)"]